{% set name = "geographiclib" %}
{% set version = "1.52" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geographiclib-{{ version }}.tar.gz
  sha256: ac400d672b8954b0306bca890b088bb8ba2a757dc8133cca0b878f34b33b2740

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - geographiclib
    - geographiclib.test
  commands:
    - pip check
    - python -m unittest -v geographiclib.test.test_geodesic
  requires:
    - pip

about:
  home: https://geographiclib.sourceforge.io/html/python/
  license: MIT
  license_file: LICENSE.txt
  license_family: MIT
  summary: The geodesic routines from GeographicLib

  description: |
    This implements algorithms for geodesics (Karney, 2013) for solving the
    direct and inverse problems for an ellipsoid of revolution.
  doc_url: https://geographiclib.sourceforge.io/html/python/
  dev_url: https://sourceforge.net/projects/geographiclib/

extra:
  recipe-maintainers:
    - QuLogic
    - cffk
    - ocefpaf
