{% set version = "1.50" %}

package:
  name: geographiclib
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/geographiclib/geographiclib-{{ version }}.tar.gz
  sha256: 12bd46ee7ec25b291ea139b17aa991e7ef373e21abd053949b75c0e9ca55c632

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - geographiclib
  commands:
    - python -m unittest -v geographiclib.test.test_geodesic

about:
  home: https://geographiclib.sourceforge.io/html/python/
  license: MIT
  license_family: MIT
  summary: 'The geodesic routines from GeographicLib'

  description: |
    This implements algorithms for geodesics (Karney, 2013) for solving the
    direct and inverse problems for an ellipsoid of revolution.
  doc_url: https://geographiclib.sourceforge.io/html/python/
  dev_url: https://sourceforge.net/projects/geographiclib/

extra:
  recipe-maintainers:
    - QuLogic
    - cffk
    - ocefpaf
