travis:
  secure:
    BINSTAR_TOKEN: F+/pFdjgYhBwEhsfRGApaQSn//hXJIBFIaTUFBI9y8ekdq09fXrAky8hXJYpSCeO/lgmqycwVFxF6SkmT3VwZixuqFodLke6/TjY5sFlHZiW/v53oTF9kdpA5lgGVPldF7mlO+eiY7ppB/urr/zQ1i0GSPKaxWJOsDVQVEW9Zczykcn97gBxDSDJdlA/KK7R/tVJWN6ElUdRORGJxJe1TFKLPI/O/ukAzQUTUAxKECsHmxzp7jSv2D9vDb/bbvKnTytqTGfCSLIPaXQQWA567Gs4O/Iu4q+RzTpGo9bPfLGpBY9sgrJicXRHJck59J5fcN1pKBgsLqds7bTPXn78H/ZvSLtdtf6ughA86HBvpjZuEztPm8wPGu3qslEh4HD5Hm9M0OeIRUCA23lSAKdEkrO3up7qToSiX0oPQi2O3DFpioNUKNC2a8MjdUUPNtUmtS191Hf6DstF1gOYlBb8w3M4S3nnwjlqQrBC0Wm5XjTJVMQRIv2hOaZjhlNz9i4zeLidpFfkrn9gyw9NqSdEyQMD0Ik9Hchla6KUYZmgavCUHhegwnEcoTAso9Min3ZCj+EKOTQiXZT2iaA/HFMcNSjrDzIkuGDy1XiSQQXr6K0SMjNLSiOaOdE1xf7RFUspWdX53ZtOq9h3Eo/DoPMjGYHLew/i/32AADzqHC3OdRg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
