travis:
  secure:
    BINSTAR_TOKEN: FQB/evezJa0qmwHci02faXrA8dafoeCbYn1OPBzdsRSijXu8U9Jp4JCu4TJmMs2xJ2BUnMSOi0js3UrRNEOFIy1SvbN3loG/UTg3Vvf6hu1INxR2+A0nBRRew6r1EO7h1fF1qIjYMhB8MFmU6e4LLRbxN0kRSM6GI5hBEG76B1RX+WOn/0xc/ipG7FLJeadYnBSQfBr/poL1i5wDk3uC6hMgw11xnbV80ZvCKJevZGHg+zbKkumzkuJkuLgIQfiL6WS07RJtTgkbRXMm+5tCfut+u79hkqPv0SlfzVNjOPdsT1Iup5cEOcB9jhV0f6k1nLOYcXmqSIYVXH5UjLe9nwACAnbkcuL1gYKTCBQQTqPmX4e532gKXk8sb0Qzlq9vlLp58mpI9RR1meMywMcNXvt4PsTpB6lrp5heSulTCTmZU+tCcsOvxDN8ueIGyrXUCF8NtaiY3K0Ad5rPHK73e/Lvv56h2jPvR8WolC4Lut3WIFvjdxtNXzWfsHFyED4avImGB51y9UgIRhF92wS+Si/rqb8FSA629kReiMFPh9PTASERdG0mbFO25L5YrieHThzDyvsRebSe+7jIZw7103azceO3BQ8oRLSRXcq2x/jykG/9VrOP+gyMs6sv38y14Ij8a/pKNHp9ubga2r0YgKorZza2VMfgRyaArcecBlg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
